### ISSUE TITLE
output/input types should be changed.

### ISSUE THREAD

**Issue by cchance27** [thoddnn/ComfyUI-MLX#4]
I notice that the MLX inputs/outputs aren't compatible with the standard items, so can't use a standard model intot he ksampler etc, so i think you should change the expected types to something like mlx_model to block people making the mistake

**Comment by thoddnn** [comment]
Hello @cchance27,

Thank you for your feedback! 🙏

You are absolutely right. I’ll make the changes early next week.

Have you tried connecting the MLX Sampler with any SDXL model or others? Let me know so I can prioritize the next feature update.

**Comment by thoddnn** [comment]
Update pushed ! New basic workflow here: https://github.com/thoddnn/ComfyUI-MLX/blob/main/workflows/basic_workflow.json
